### ISSUE TITLE
Tarea de prueba

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#1]
Hola manga de Topus......

**Comment by leoimoli** [comment]
Hola Ale

**Comment by AleeWalsh** [comment]
Hola jefe

**Comment by leoimoli** [comment]
Hola Chicos!!!! Manden Algo acá para ver si anda.

**Comment by silvestriandres** [comment]
Probando mandar un comentario :P

**Comment by alewalsh** [comment]
anda de 10

**Comment by leodimonio** [comment]
USA USA USA!!!!

**Comment by rominariquelme** [comment]
+1:

**Comment by mpgarcia** [comment]
Hola Jefe.
pd: Ticky arreglame el servicio, hoy vacunamos a USA. 
pd2: Andres hace streaming de tu juego.

**Comment by silvestriandres** [comment]
@leodimonio testing.-
