### ISSUE TITLE
Cambios Base De Datos

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#10]
Necestiamos cambiar en la Base de datos sinalic_prod en la tabla tClasesLicencias lo detallado en el excel adjunto.
Solo se debe modificar las resaltadas en color verde.

[DescripcionesClases (2).xlsx](https://github.com/leoimoli/Sinalic/files/337032/DescripcionesClases.2.xlsx)

**Comment by rominariquelme** [comment]
Se realizaron los cambios de la tabla tClasesLicencias  de la  Base de datos Sinalic_pod

**Comment by leoimoli** [comment]
Se informo a la Dir.de Licencias que ya se subio el cambio a testing.
