### ISSUE TITLE
Pasaje a Testing Panel de Licencias

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#11]
Subir a testing la versión del panel de licencias.

**Comment by silvestriandres** [comment]
Se subió a testing la versión actualizada del Panel de Licencias, con la siguiente URL:
http://testing02.seguridadvial.gov.ar/PanelLicencias.Web/ 
Habiéndose actualizado tanto el servicio web como el sitio web.-
Resta llevar a cabo pruebas con relación a las actualizaciones diarias que se han de reflejar en el sistema.-

**Comment by silvestriandres** [comment]
La siguiente es la URL del repositorio correspondiente tanto al sitio como al servicio web:
https://repo.ansv.gov.ar:8443/svn/RepoSINALIC/repoMonitor

**Comment by leoimoli** [comment]
11/07/2016: Se subió a testing la versión del panel Licencias.
