### ISSUE TITLE
Pasaje a Testing V- 1.8

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#12]
Necesitamos subir a Testing la version 1.8 de SINALIC Web.

Incluye Tickets(#3--#5--#6)

**Comment by silvestriandres** [comment]
Se realizó el pasaje a testing de la versión 1.8, como esta actualmente.
La URL del sitio en testing es la siguiente:
URL: http://testing02.seguridadvial.gov.ar/Sinalic.Testing
