### ISSUE TITLE
V-1.8 Nuevo Requerimiento

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#13]
Necesitamos que al momento de generar un tramite(FUT) guardemos la versión de SINALIC y desde el servidor donde se genero el tramite.

Trabajar en la Versión: 1.8

**Comment by leoimoli** [comment]
Va

**Comment by silvestriandres** [comment]
Se actualizó la versión 1.8 con los cambios requeridos para que al guardar el trámite se guarde también el nombre del server y la versión.-
Por otro lado se adjuntan las querys que se vienen usando para esta versión,.-
[Querys_1_8.txt](https://github.com/leoimoli/Sinalic/files/357785/Querys_1_8.txt)
La URL del sitio en testing sigue siendo la misma:
testing02.seguridadvial.gov.ar/Sinalic.Testing
