### ISSUE TITLE
Nuevo Requerimiento

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#14]
De la dirección de licencias nos solicitan agregar unos cambios SOLO para córdoba capital. 

Los mismos son: 

Subclase D1 a partir de los 18 años 
Clase C vigencia 5 años 
1 año periodo de gracia 

Como no se sabe si se aplica a WS o a frontend, se pide que se desarrolle en ambos lados. 

Trabajar en la versión Front(1.8) y Servicios (1.8)

Ticket N°38851

**Comment by leoimoli** [comment]
Solo trabajar la parte Front.

**Comment by silvestriandres** [comment]
Se actualiza la tarea tanto para Front como para WebService:
La localidad que se tuvo en cuenta es la localidad de ID = 20071
y los centros de emisión van del ID = 497 al 510

La url del Front sería la siguiente: 
http://testing02.seguridadvial.gov.ar/Sinalic.Testing2/

La publicación del ServicioWeb no está hecha, pero si está commiteado.
