### ISSUE TITLE
Arreglo Panel Licencias

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#16]
*El:
se le cargo licencias a la provincia CHUBUT, al actualizar el panel muestra TOTAL, HOY, y Última actualización.
El "HOY" trae bien la licencias.
EL "TOTAL" no actualiza sigue apareciendo la misma cantidad de lic.
La "ÚLTIMA NOVEDAD" pone a todas las provincias con la última actualización ej: "11-Jul-16".

*CEL:
en los centros pasa mas o menos lo mimos;
el "HOY" lo trae bien pero no suma el "TOTAL" 
y "ÚLTIMA NOVEDAD" ACTUALIZO en todos los centros con la fecha de hoy menos en "obera" que fue donde yo le cargué lic.

*CENTRO DE EMISIÓN: OBERA: no carga como que en julio se emitieron lic.

**Comment by silvestriandres** [comment]
Se llevaron a cabo los cambios referentes en el servicio web, por otro lado, la fecha de última novedad queda actualizar el proceso en sql, pero lo hizo ruben y quedó en actualizarlo.-

las url son las siguientes.
WEB: http://testing02.seguridadvial.gov.ar/PanelLicencias.Web/
SERVICIO: http://testing02.seguridadvial.gov.ar/PanelLicencias.Servicio/
