### ISSUE TITLE
V -1.8 Nuevo Requerimiento(GLPI 1443)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#17]
En el FUT, donde dice "teléfono", debe salir el numero de celular y no el teléfono particular.

Trabajar en la versión 1.8

**Comment by rominariquelme** [comment]
Se cambio el parametro de teléfono por celular.

**Comment by leoimoli** [comment]
Revision SVN(1459)

**Comment by leoimoli** [comment]
Reportan De testing lo siguiente:
solo aparece CELULAR al dar de alta la persona, en el fut sigue apareciendo TELÉFONO, y tmb aparece desalineado NAC Y EMAIL Y FECHA NAC.. ADJUNTO CAPTURA DE PANTALLA 

![fut1](https://cloud.githubusercontent.com/assets/11543134/17062416/3eb6c054-5009-11e6-93cd-d7c1e0b6dc0b.png)

**Comment by rominariquelme** [comment]
Se alinearon los campos y se cambio la palabra 'Teléfono' por 'Celular' de los FUT.

**Comment by leoimoli** [comment]
Se subio a testing el 26/09.
