### ISSUE TITLE
V- 1.8 Nuevo Requerimiento SINALIC WEB(GLPI 1435)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#18]
Desde la Provincia de Rio negro nos informan que el escudo que sale impreso en la Licencia Nacional no esta actualizado.
Adjunto el escudo actual para su modificación.

Trabajar en la Versión 1.8 
![escudo rio negro](https://cloud.githubusercontent.com/assets/11543134/16845167/55ec9d1c-49be-11e6-989c-0d092c4fbb3b.jpg)

**Comment by rominariquelme** [comment]
Se actualizó el escudo de la Pci de Rio Negro

**Comment by leoimoli** [comment]
Revision SVN(1460--1461)

**Comment by leoimoli** [comment]
Reportan desde Testing: 

(al querer imprimir la licencia del cel Rio Negro el logo no sale, sale la famosa cruz roja Y LA FIRMA PARECE QUE SALE MAL . ADJUNTO CAPTURA DE PANTALLA )
![lic1](https://cloud.githubusercontent.com/assets/11543134/17062786/c70febe6-500a-11e6-8e54-4be4907851fb.png)
![lic2](https://cloud.githubusercontent.com/assets/11543134/17062787/c7102ebc-500a-11e6-9f6f-f53b394db8ea.png)

**Comment by rominariquelme** [comment]
Se modifican el nombre del archivo para que se vea el escudo del CEL de Río Negro y se arreglo la firma.

**Comment by leoimoli** [comment]
Se subio a testing el 26/09.
