### ISSUE TITLE
V- 1.7.6 Error produccion(GLPI 1716)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#19]
Este cambio nos sigue trayendo problemas con la foto al momento de hacer el FUT.

1- Se actualizó el front para que muestre una imagen por defecto a la hora de mostrar trámites o licencias que no tienen foto.
Te deja iniciar un trámite sin haber sacado o confirmado la foto
Necesitamos que vuelva a salir el cartel que decía "la foto es obligatoria" y no permita generar el tramite.

Se debe trabajar en el branch productivo 176

**Comment by silvestriandres** [comment]
Se llevo a cabo la re-inclusión de la validación, tanto para la foto como para la firma (por las dudas), se hizo un chequeo y se pasó también en la versión 1.8 (alineado).-
