### ISSUE TITLE
V- 1.8 Nuevo Requerimiento(GLPI 1721)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#21]
Anular Licencia: Se deberán Agregar motivo y fecha de eliminación de la licencia.

**Comment by leoimoli** [comment]
Reportan desde testing:

Al querer consultar la licencia que se anuló correctamente, al buscarla por número de licencia tira el siguiente error. Value was either too large or too small for an Int32.

![image 1](https://cloud.githubusercontent.com/assets/11543134/17062677/4f6923d2-500a-11e6-9fc4-5df008545048.png)

**Comment by rominariquelme** [comment]
Se resuelve el error cambiando el tipo de dato.
