### ISSUE TITLE
V- 1.8 Mejora - Agregar Mail o Celular - (GLPI 1720)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#23]
Se deberá agregar como dato obligatorio el email "O" el celular.

**Comment by rominariquelme** [comment]
Se agrego como dato obligatorio el mail o el celular. Modificacion de la funcion ValidarCampos de Fuentes/Sinalic.Present/WUCPresenters/PersonaPresenters.cs
