### ISSUE TITLE
V-1.8 Modificar Dorso Licencia PDF

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#25]
Modificar las medidas del código PDF 247. Las medidas están el la hoja que tiene Andres.

**Comment by silvestriandres** [comment]
Se actualizó el tamaño del código PDF417, y se testeo con las PDA (tanto las actuales como con las nuevas), está desarrollado, pero no se commiteó ni se publicó.-

**Comment by leoimoli** [comment]
Se subio a testing el 26/09.
