### ISSUE TITLE
SINALIC V-1.8

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#26]
En la creación del Centro emisor de licencias se debe agregar un campo a completar "CEL" del cual el sistema tomara el nombre para generar el PDF.

**Comment by silvestriandres** [comment]
Se actualizó la versión 1.8 de SINALIC, ahora al agregar o editar un CEL, hay un campo extra para agregar el texto que se desea mostrar en la parte superior izquierda de la licencia, en caso de que no se llene, se sigue usando la lógica actual.-
