### ISSUE TITLE
SINALIC -- Nuevo Metodo Certificado de Legalidad

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#27]
CERTIFICADO DE LEGALIDAD: En el Repo esta la documentación actualizada para desarrollar el nuevo método. Se les dijo que estaba para fines de la semana que viene.  
[SINALIC- Introducción a las Funcionalidades de WS .docx](https://github.com/leoimoli/Sinalic/files/495609/SINALIC-.Introduccion.a.las.Funcionalidades.de.WS.docx)

[SINALIC WS- Descripción de los Servicios Web.docx](https://github.com/leoimoli/Sinalic/files/495614/SINALIC.WS-.Descripcion.de.los.Servicios.Web.docx)
[SINALIC WS- Especificación de los Servicios Web.docx](https://github.com/leoimoli/Sinalic/files/495613/SINALIC.WS-.Especificacion.de.los.Servicios.Web.docx)

**Comment by silvestriandres** [comment]
Se agregó el nuevo método ConsultarLicenciaCertificado, que retorna los datos requeridos para el certificado de legalidad.

Se commitió, y a la hora de publicarlo habrá que comentar todos los otros métodos si es que no se quieren mostrar al exterior.-
