### ISSUE TITLE
SINALIC - Verificar Restriccion cordoba (GLPI 3472)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Sinalic#29]
pedilo de Albita (foxy lady)

DNI 16167669.Oviedo carlos Alberto 
error código es el 54, la fecha de vencimiento de la licencia debe ser menor a la vigencia máxima.
La persona tramitó una licencia previa que contiene las clases A21 Y B2 con vigencia hasta 14/09/2021 y ahora está realizando una ampliación con cambio de clase a D3 cuya vigencia debe ser hasta 19/09/2018, por lo cual es menor al plazo maximo de 2 años.

**Comment by silvestriandres** [comment]
Está chequeado con el código y las restricciones particulares para Córdoba, te dejo escrito lo que le respondería en el ticket.

=============================================================
Buenas que tal Alba, te comento que inicialmente, según tengo entendido las restricciones para Córdoba se pidieron para los siguientes tipos de Trámite (Original, Renovación y Renovación con Ampliación), con lo cual, si es como me comentás que lo que están tratando de hacier es una "Ampliación con Cambio de Clase", no estaría usando las validaciones de Córdoba.

En caso de que quisieran usar las validaciones para otros tipos de trámite, por favor avisar para que tipos de trámites (o si directamente es para todos),, cosa de coordinar y pasar el cambio a producción.
=============================================================
