### ISSUE TITLE
Cambio de tamaño de pdf 417

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Sinalic#30]
Cambio del tamaño de pdf417 , pedido por mail de alba bruno

**Comment by silvestriandres** [comment]
Se generaron los PDFs. y se respondió el mail a Licencias.-

[licencia10139490 (4,5 - 1,277).pdf](https://github.com/leoimoli/Sinalic/files/522019/licencia10139490.4.5.-.1.277.pdf)
[licencia10139490 (3,0 - 0,7).pdf](https://github.com/leoimoli/Sinalic/files/522021/licencia10139490.3.0.-.0.7.pdf)
[licencia10139490 (3,5 - 0,817).pdf](https://github.com/leoimoli/Sinalic/files/522020/licencia10139490.3.5.-.0.817.pdf)
[licencia10139490 (4,0 - 0,933).pdf](https://github.com/leoimoli/Sinalic/files/522023/licencia10139490.4.0.-.0.933.pdf)
[licencia10139490 (4,5 - 1,15).pdf](https://github.com/leoimoli/Sinalic/files/522022/licencia10139490.4.5.-.1.15.pdf)
