### ISSUE TITLE
SINALIC - Verificar Restriccion cordoba (GLPI 3472)

### ISSUE THREAD

**Issue by leodimonio** [leoimoli/Sinalic#31]
Andresito te copio como viene el seguimiento del tema, lo agrego al github para tenerle el seguimiento tambien
Seguimiento :
5)genial, cuando este realizado el cambio coordinamos cuando lo subimos.
4)Buenas Alba que tal, el cambio es muy sencillo, ponele que lo hagamos entre hoy y mañana, y luego restaría coordinar para hacer el pasaje a producción del servicio web de Córdoba.-
3)Las restricciones las necesitamos para todos los tipos de tramite. Esos 3 que nombras se pidieron para una primera etapa, y al momento de solicitar para los demas tipos de tramites me respondieron que se hicieron para todos-. necesitamos que incluyasn los demas tipos de tramites.
2)Buenas que tal Alba, te comento que inicialmente, según tengo entendido las restricciones para Córdoba se pidieron para los siguientes tipos de Trámite (Original, Renovación y Renovación con Ampliación), con lo cual, si es como me comentás que lo que están tratando de hacier es una "Ampliación con Cambio de Clase", no estaría usando las validaciones de Córdoba. En caso de que quisieran usar las validaciones para otros tipos de trámite, por favor avisar para que tipos de trámites (o si directamente es para todos),, cosa de coordinar y pasar el cambio a producción.

1)DNI 16167669.Oviedo carlos Alberto error código es el 54, la fecha de vencimiento de la licencia debe ser menor a la vigencia máxima. La persona tramitó una licencia previa que contiene las clases A21 Y B2 con vigencia hasta 14/09/2021 y ahora está realizando una ampliación con cambio de clase a D3 cuya vigencia debe ser hasta 19/09/2018, por lo cual es menor al plazo maximo de 2 años.

**Comment by silvestriandres** [comment]
Este fue el cambio que se pasó a producción para Córdoba el lunes 24/10/2016, con lo que ahora se incluye en Córdoba todos los tipos de trámite.-
