### ISSUE TITLE
PROBLEMAS CON FUT MAL GENERADO(GLPI 4003)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#33]
Seguimos con problemas en la impresión de los FUT, los mismos salen con las letras de los nombres y apellido montadas entre si. 

Repositorio: https://repo.ansv.gov.ar:8443/svn/RepoSINALIC/branches/Fuentes_Web_1.8

**Comment by rominariquelme** [comment]
Se arreglo la superposición de letras.
