### ISSUE TITLE
error version 1.8(GLPI 3830)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#34]
En las Licencias que se generan con los centros satelites la firma del funcionario sale con un espacio entre el nombre y el cargo.

Adjunto Licencia del cel de San Luis (Centro Administrador) y de la sede Sur de San Luis (Centro Satelite)

**Comment by silvestriandres** [comment]
Se actualizó el reporte de la licencia para que no se genere ese renglón extra, sin necesidad de mover o tocar el código qr.-
