### ISSUE TITLE
Error produccion 1.8(GLPI 4097)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#35]
Restricciones Formosa clase A3, el sistema le da una vigencia de 3 años sin importar la edad, les paso las vigencias.

19 a 20 - 3 años
21 a 65 - 5 años
66 a 70 - 3 años
mas de 71 - 1 año

Se aclara que las vigencias a partir de los 21 años son iguales a la ley nacional, por lo que solo la excepción es para las personas de 19 y 20 años. les paso 2 casos donde el sistema dio 3 años de vigencia: 14622712 26265288

**Comment by silvestriandres** [comment]
Resta por confirmar si la antigüedad para mayores de 21 se mantiene como esta a nivel nacional (así está actualmente) o es de 1 año en la A.2.2 como la excepción que se agregó para Formosa para las personas de 19 a 20.-
