### ISSUE TITLE
Restricciones Para Centro de Entre Rios (GLPI 4246)

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#36]
Se necesita la siguiente restricción para el CEL Colonia Avellaneda, Entre Rios

A.2.1 a partir de los 16 años, sin antigüedad en A1.

**Comment by leoimoli** [comment]
Trabajar en la version Branch 1.8.1
URL Repo: https://repo.ansv.gov.ar:8443/svn/RepoSINALIC/branches/Fuentes_Web_1.8.1

**Comment by silvestriandres** [comment]
Se actualizó la versión 1.8.1, que para dicho centro, no pida antigüedad a partir de los 16 en la clase A.1
