### ISSUE TITLE
Servicios WEB 1.9 Agregar Campo CUIL

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#39]
1) En el metodo inserta licencia anterior se debe agregar un nuevo campos "CUIL"

[SINALIC WS- Especificación de los Servicios Web.docx](https://github.com/leoimoli/Sinalic/files/676122/SINALIC.WS-.Especificacion.de.los.Servicios.Web.docx)

2) En Licencia Anterior validar que cuando nos envien 0 en el IDLocalidad ponerlo en algun valor logico y continue el circuito normal.

**Comment by silvestriandres** [comment]
Se agregaron ambos campos.
Para respetar la lógica ya existente en sinalic con respecto al CUIL de la persona, este campo pasó a ser de 11 caracteres y no de 13 como inicialmente se había pensado.
