### ISSUE TITLE
SINALIC Nuevo Campo Cuil

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#41]
Se debe trabajar en el branch 1.9.2 de SINALIC Front.

[DI-RDES25 - Especificaciones de Requisitos de Software _SINALIC_20.docx](https://github.com/leoimoli/Sinalic/files/689939/DI-RDES25.-.Especificaciones.de.Requisitos.de.Software._SINALIC_20.docx)

**Comment by silvestriandres** [comment]
Se actualizó la versión, restaría publicar en testing y correr los scripts en la base que corresponda.
El deploy está para bajarlo en la siguiente carpeta del repositorio:
https://repo.ansv.gov.ar:8443/svn/INFORMATICA/Proyectos/Sinalic/Desarrollo/Branches/Fuentes_Web_1.9.2/Deploys/V_1.9.2_A
