### ISSUE TITLE
Pasaje a Testing V-1.7.6

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#7]
Andres, subir  la versión 1.7.6 de SINALIC a testing.

**Comment by silvestriandres** [comment]
Se publicó la versión en testing con los últimos cambios solicitados.
La url es la siguiente: http://testing02.seguridadvial.gov.ar/Sinalic.Testing/

**Comment by leoimoli** [comment]
Ya se aviso al Dpto de análisis de la subida.

La version cuenta con los tickets(#2--#4)

**Comment by leoimoli** [comment]
El día 05/07/2016 se subió en la Rioja la versión a producción. Esperando confirmación para el resto del país.

**Comment by leoimoli** [comment]
El día 06/07/2016 se subió a testing la versión de Sinalic Web.
