### ISSUE TITLE
Ticket N°38832

### ISSUE THREAD

**Issue by leoimoli** [leoimoli/Sinalic#8]
Generar PDF de la Licencia DNI: 23857685.

**Comment by silvestriandres** [comment]
Se sacó el pdf de la licencia.-

[licencia23857685.pdf](https://github.com/leoimoli/Sinalic/files/330347/licencia23857685.pdf)

**Comment by leoimoli** [comment]
Se envio el pdf a la gente del Dpto de Analisis.
